package:
  name: xni
  version: 0.5.0

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - anaconda
#   - ipyparallel

about:
  home: https://github.com/hyounggyu/xni
  license: GPL
