CACHE_DIR = '/tmp/'

WEBSERVER_HOST = '127.0.0.1'
WEBSERVER_PORT = 8000
WEBSERVER_URI  = 'http://{}:{}'.format(WEBSERVER_HOST, WEBSERVER_PORT)

VENTILATOR_HOST = '127.0.0.1'
VENTILATOR_PORT = 9305 # IU's birthday (1993-May-16)
VENTILATOR_URI  = 'tcp://{}:{}'.format(VENTILATOR_HOST, VENTILATOR_PORT)

SINK_HOST = '127.0.0.1'
SINK_PORT = 9410 # Suzy's birthday (1994-Oct-10)
SINK_URI  = 'tcp://{}:{}'.format(SINK_HOST, SINK_PORT)
